services:

    assoconnect_mjml.custom_compiler:
        class: Assoconnect\MJMLBundle\Compiler\CustomCompiler
        arguments:
            $tags: !tagged assoconnect_mjml.custom_tag

    assoconnect_mjml.compiler:
        class: Assoconnect\MJMLBundle\Compiler\Compiler
        arguments:
            $customCompiler: "@assoconnect_mjml.custom_compiler"
            $mjmlCompiler: "@assoconnect_mjml.mjml_compiler_service"
            $cacheDir: "%kernel.cache_dir%"

    assoconnect_mjml.rest_mjml_compiler_client:
      class: GuzzleHttp\Client
      public: true
      arguments:
        - base_uri: '%assoconnect_mjml.rest_mjml_compiler_host%'

    assoconnect_mjml.rest_mjml_compiler:
        class: Assoconnect\MJMLBundle\Compiler\RestMjmlCompiler
        arguments:
            $client: "@assoconnect_mjml.rest_mjml_compiler_client"

    assoconnect_mjml.mjml_compiler_service:
      alias: assoconnect_mjml.mjml_compiler

    assoconnect_mjml.mjml_compiler:
        class: Assoconnect\MJMLBundle\Compiler\MjmlCompiler

    assoconnect_mjml.template_finder:
        class: Assoconnect\MJMLBundle\Finder\TemplateFinder
        arguments:
            $projectDir: "%kernel.project_dir%"
            $templatePaths: "%assoconnect_mjml.template_paths%"

    assoconnect_mjml.cache_warmer:
        class: Assoconnect\MJMLBundle\CacheWarmer\CompileCacheWarmer
        tags:
            - { name: "kernel.cache_warmer", priority: 50 }
        arguments:
            $compiler: "@assoconnect_mjml.compiler"
            $templateFinder: "@assoconnect_mjml.template_finder"

    assoconnect_mjml.command:
        class: Assoconnect\MJMLBundle\Command\CompilerCommand
        tags:
            - { name: "console.command" }
        arguments:
            $compiler: "@assoconnect_mjml.compiler"
            $templateFinder: "@assoconnect_mjml.template_finder"
            $projectDir: "%kernel.project_dir%"
